title: Najib Chowdhury
#logo: 
#description:
#show_downloads: true
base: "https://najibchy.github.io"

theme: jekyll-theme-minimal

plugins:
  - jekyll-feed

navigation:
  - title: "Home"
    url: "/'
  - title: "About"
    url: "/about/"
  - title: "Contact"
    url: "/contact/"
  
